import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Shortly URL shortening API Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
      </Head>

      <div className="page-intro row">
        <div className="col-md-6">
          <div>
            <div className="title display-4">
              More than just <br /> shorter links
            </div>
            <div className="muted-desc">
              Build your brand’s recognition and get detailed insights on how
              your links are performing.
            </div>
            <div className="intro-action">
              <div className="md-btn-primary">Get Started</div>
            </div>
          </div>
          <div></div>
        </div>

        <div className="col-md-6">
          <img width="100%" src="/images/illustration-working.svg" />
        </div>
      </div>

      <div className="url-form-sect-cont">
        <div className="url-form-sect-1">
          <div className="url-form-sect row">
            <div className="col-md-9 pt-2">
              <input type="text" placeholder="Shorten a link here..." />
            </div>
            <div className="col-md-3 pt-2">
              <button className="btn-shorten"> Shorten it! </button>
            </div>
          </div>
        </div>
      </div>

      <div>
        <div>
          <div>
            <div>https://www.frontendmentor.com</div>
            <div>
              <div>https://rel.ink/k334i4</div>
              <div>Copy</div>
            </div>
          </div>
        </div>
      </div>

      <div className={styles.sect__2}>
        <div className={styles.adv__stats__cont}>
          <div style={{ textAlign: "center" }}>
            <div style={{ fontSize: "25px", fontWeight: "700" }}>
              Advanced Statistics
            </div>
            <div className={styles.adv__track}>
              Track how your links are performing across the web with
            </div>
            <div className={styles.adv__track}>
              our advanced statistics dashboard.
            </div>
          </div>
        </div>

        <div className={styles.brand__recog__cont}>
          <div className="row">
            <div className="col-lg-4 card-item-cont">
              <div className="card-item">
                <div className="card-item-title">Brand Recognition</div>
                <div className="card-item-desc">
                  Boost your brand recognition with <br /> each click. Generic
                  links don’t mean a <br /> thing. Branded links help instil{" "}
                  <br /> confidence in your content.
                </div>
              </div>
            </div>
            <div className="col-lg-4 card-item-cont">
              <div className="card-item">
                <div className="card-item-title">Detailed Records</div>
                <div className="card-item-desc">
                  Gain insights into who is clicking your <br /> links. Knowing
                  when and where
                  <br />
                  people engage with your content <br /> helps inform better
                  decisions.
                </div>
              </div>
            </div>
            <div className="col-lg-4 card-item-cont">
              <div className="card-item">
                <div className="card-item-title">Fully Customizable</div>
                <div className="card-item-desc">
                  Improve brand awareness and content <br /> discoverability
                  through customizable <br />
                  links, supercharging audience
                  <br /> engagement.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="link-boost-sect">
        <div
          className={`d-flex`}
          style={{ flexDirection: "column", alignItems: "center" }}
        >
          <div style={{ paddingBottom: "13px", fontSize: "18px" }}>
            Boost your links today
          </div>
          <div className="md-btn-primary">Get Started</div>
        </div>
      </div>
    </div>
  );
}
